### ISSUE TITLE
Audio intermittently cuts out when video is speeded up

### ISSUE THREAD

**Issue by rnglnd** [FrontendMasters/ios-issues#35] opened 2018-11-22 09:22 UTC
## Issue Description
When video is at least af 1.2x the audio intermittently cuts out.

### Preconditions
Device: iPhone 7 Plus or 2017 iPad, iOS version 12.1

### Steps to Reproduce
1. Log in
2. Navigate to Courses Index
3. Play any course
4. Put speed to at least 1.2 but best results seen on 2.0
5. Let course run for a bit

### Actual and Expected Result
Expected:
Audio should never cut out

Actual:
Cuts out often over the duration of the course

**Comment by jessepeterman** [comment] 2018-11-29 22:56
I’m having the same problem on iPhone 5s.

**Comment by venikx** [comment] 2019-01-27 07:49
Device: iPhone xr, version: 12.1.2.

Same issue, a way to remedy it is to switch the orientation (might not br related at all).
If I go back 15s before the audio cut and change to a lower speed it sometimes remedies it.

A last resort is to shut down the app completely.

Edit: It happens more often in fullscreen mode. I was able to trigger it kinda frequently by setting the speed to 1.8x and switch to fullscreen mode.

**Comment by dachev** [comment] 2019-01-30 15:57
@AnaRobynn, @jessepeterman, @rnglnd I haven't been able to reproduce this on any of my devices.

Apple doesn't expose a lot of levers that can affect the audio experience other than pitch correction. We are using the lowest quality suitable for human voice so this shouldn’t be very taxing on the device. Short of flaws in the media stream, the rest of the audio experience is completely in the hands of iOS.

I've compiled a list of questions hoping that something will jump out. Can you please take a moment and answer as many as you can.

1) When the audio is lost, does the video stall as well?
2) Does it tend to loose audio at the same positions or does it happen randomly?
3) How long is the audio lost for usually - seconds at a time, or shorter and choppy?
4) Have you noticed any patterns - time of day, days of week, days of month.
5) @jessepeterman, @rnglnd Has it happened recently?
6) Does it only happen with a specific course(s)?
7) Can you give me an example course it happened with?

Thanks for taking the time to report this issue and helping us make FEM better,
Blago

**Comment by venikx** [comment] 2019-01-30 17:14
@dachev Thanks for looking into it!

1. No video keeps on going
2. It happens at the same position, however sometime changing the speed or orientation will make the sound not go away
3. There are multiple case:
- drops for a couple seconds and comes back
- drops for a longer period of time and switching orientation can make it come back
- drops for the whole video

I've also noticed that these effects are getting worse and longer when using the application for a while. So the longer you spend on frontend masters the more annoying it gets. 
Usually completely closing down the app "resets" the annoyances.

4. No patterns
6. Every course I've watched so far has this issue
7. CSS Grid, Introduction to React, Intermediate React, Unit Testing Javascript (with coffescript), Testing and Modular front-end.

I hope this helps!

**Comment by rnglnd** [comment] 2019-02-08 15:14
@dachev Sorry for the delay in getting back to this and thanks for looking at it! I agree with @AnaRobynn but will also fill in the answers:

1. No
2. Random for me
3. Appears to be random also but usually it's multiple seconds for me.
4. No
5. Yes, happens every time I use the app
6. No
7. There are some examples above but just to add more: Scott Moss Node v2, all the Sean Larkin Webpack courses.

Also I use a VPN from time to time on my phone and it appears to be worse when I do. I did also notice @AnaRobynn was in Europe as well so I assumed it could've been a latency thing, do you have servers in the EU? However, I also noticed @jessepeterman is not and has had issues so it may not be the case. Maybe worth trying out though if you've a VPN or some way of replicating that.

**Comment by dachev** [comment] 2019-03-09 16:16
Thank you @AnaRobynn @rnglnd . Does this also happen when you play an offline (downloaded) video?

**Comment by rnglnd** [comment] 2019-03-11 20:39
@dachev I just did a quick test and it doesn't appear to. The test I ran is listed below:

- Watched a video and observed it happening
- Downloaded said video and watched it again. It didn't happen
- The next video in the series it did happen again.

**Comment by jessepeterman** [comment] 2019-03-11 20:44
I tested it out yesterday, and it looks like it still does it with downloaded videos. I can double check later today though.

**Comment by LA** [comment] 2019-09-15 17:29
This happens to me on streamed (not downloaded) videos as well. Audio randomly cuts out periodically (and for longer periods the faster the speed is) unless I play on 1x speed.

iPhone 7 Plus, 12.4.1. I’ve only watched Kyle Simpson videos but it happens on all of them at greater than 1.2x.

**Comment by dpkahuja-jg** [comment] 2020-05-21 11:52
Same problem, I was watching Intro to containers by brian holt.
Device iphoneXR

**Comment by dachev** [comment] 2024-04-08 14:48
This should've been fixed in a prior release.

**Closed as completed by dachev** 2024-04-08 14:48 UTC
