### ISSUE TITLE
Iphone app crasing

### ISSUE THREAD

**Issue by devbrunopaula** [FrontendMasters/ios-issues#47] opened 2020-08-25 18:04 UTC
App crashes as soon as I click to view a video.

**Comment by dachev** [comment] 2020-08-26 03:42
Hi Bruno,
Can you share some more details on how to reproduce this crash? Does it happen with any or only specific course? Are you able to see the course details (e.g. lesson list) at all? Does still crash if you disable auto-play from the settings?

**Comment by dachev** [comment] 2020-08-29 12:36
@devbrunopaula It looks like you are running the iOS 14 beta release. The stack trace indicates that the crash originated in Apple's UIKit. I'll close this ticket now but we'll keep an eye on the situation.

**Closed as completed by dachev** 2020-08-29 12:36 UTC
